### ISSUE TITLE
Change how simulation paths are looked up

### ISSUE THREAD

**Issue by MilanStaffehl** [MilanStaffehl/TNG-Cluster-paper#115]
Currently, the special role if TNG-Cluster in the config file causes a bit of an awkward situation with two simulation home paths.

Better would be to specify, for every simulation, the base path in the config file directly. Make it such that `base_paths` is atop level field of the config yaml and then allow users to add their own key-value pairs to it, like so:

```yaml
base_paths:
  TNG50: path/to/tng50
  TNG100: path/to/tng100
  TNG300: path/to/tng300
  TNG-Cluster: path/to/tng-cluster
```

The resolution can then be appended to the base path inside the `get_basic_config` function. This resolves the problem of adding simulations later, as users can add simulations at will.

Relates to:
- #97 (dissolution of `glob_util` and handling of simulation names)
